### ISSUE TITLE
Error in Pushing image to yatai

### ISSUE THREAD

**Issue by plaban1981** [bentoml/Yatai#305] opened 2022-08-04 07:48 UTC
**1.** I have  Setup initial admin account
==> $ **echo "Create admin account at: http://127.0.0.1:8080/setup?token=$YATAI_INITIALIZATION_TOKEN" && kubectl --namespace yatai-system port-forward svc/yatai 8080:80**
Create admin account at: http://127.0.0.1:8080/setup?token=1nXgqCODLhPtWNZt
Forwarding from 127.0.0.1:8080 -> 7777
Forwarding from [::1]:8080 -> 7777
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
(base) PS C:\Users\nayak\Documents\BentoML> **bentoml yatai login --api-token cbki5ojmpum0mjct3dd0 --endpoint http://127.0.0.1:8080**
Overriding existing Yatai context config: default
login successfully! user: plaban81, organization: default

(base) PS C:\Users\nayak\Documents\BentoML> bentoml push cancer_classifier:latest
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Failed to upload model "booster_tree:jjzrgfqq2kolbjcc"                                                                                                                                                         │
│ Failed pushing model "booster_tree:jjzrgfqq2kolbjcc" : HTTPConnectionPool(host='yatai-minio-yatai-infra.192.168.49.2.sslip.io', port=80): Max retries exceeded with url: /yatai/models/default/booster_tree/j… │
│ Failed to upload Bento "cancer_classifier:nfhcz6qtxkbedjcc"                                                                                                                                                    │
│ Failed pushing Bento "cancer_classifier:nfhcz6qtxkbedjcc": HTTPConnectionPool(host='yatai-minio-yatai-infra.192.168.49.2.sslip.io', port=80): Max retries exceeded with url: /yatai/bentos/default/cancer_cla… │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Pushing Bento "cancer_classifier:nfhcz6qtxkbedjcc" ------------------------------------------------------------------------------------------------------------------------------ 0.0% • 0.0/71.5 MB • ? • -:--:--
   Uploading model "booster_tree:jjzrgfqq2kolbjcc" ------------------------------------------------------------------------------------------------------------------------------ 0.0% • 0.0/4.7 kB  • ? • -:--:--

**2.** Also I encounter below error when i try to login to yatai using endpoint : http://yatai.127.0.0.1.sslip.io
 (base) PS C:\Users\nayak\Documents\BentoML> **bentoml yatai login --api-token 1nXgqCODLhPtWNZt --endpoint http://yatai.127.0.0.1.sslip.io**
Traceback (most recent call last):
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\nayak\anaconda3\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\nayak\anaconda3\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\nayak\anaconda3\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\nayak\anaconda3\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\Users\nayak\anaconda3\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000022BBE4997C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='yatai.127.0.0.1.sslip.io', port=80): Max retries exceeded with url: /api/v1/auth/current (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BBE4997C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nayak\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\nayak\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\nayak\anaconda3\Scripts\bentoml.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\nayak\anaconda3\lib\site-packages\bentoml\_internal\cli\click_utils.py", line 167, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\nayak\anaconda3\lib\site-packages\bentoml\_internal\cli\click_utils.py", line 139, in wrapper
    return_value = func(*args, **kwargs)
  File "C:\Users\nayak\anaconda3\lib\site-packages\bentoml\_internal\cli\click_utils.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\nayak\anaconda3\lib\site-packages\bentoml\_internal\cli\yatai.py", line 35, in login
    user = yatai_rest_client.get_current_user()
  File "C:\Users\nayak\anaconda3\lib\site-packages\bentoml\_internal\yatai_rest_api_client\yatai.py", line 50, in get_current_user
    resp = self.session.get(url)
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\nayak\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='yatai.127.0.0.1.sslip.io', port=80): Max retries exceeded with url: /api/v1/auth/current (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BBE4997C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by plaban1981** [comment] 2022-08-04 07:51
![yatai1](https://user-images.githubusercontent.com/23618329/182793834-4b5c978d-0cab-47ad-ade6-3f54e80b8b76.JPG)

**Comment by TheDarkTrumpet** [comment] 2022-08-04 09:28
Duplicate of https://github.com/bentoml/Yatai/issues/300 (I can't add the link myself, if one of the mods can do it)

**Comment by plaban1981** [comment] 2022-08-04 09:50
The  package versions used

OS: [Windows 10]
Python Version [Python 3.9.12]
BentoML Version [BentoML-1.0.2]
Bentoctl Version [bentoctl-0.3.3]
minikube version: [v1.26.0]

**Comment by plaban1981** [comment] 2022-08-04 14:49
I was able to push image using bentoctl by following the steps mentioned in[ [#300](https://github.com/bentoml/Yatai/issues/300)(not a permanent resolution though) . But encountered the below message
 bentoml push cancer_classifier:latest
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Successfully pushed model "booster_tree:jjzrgfqq2kolbjcc"                                                                                                                                                     │
│ Failed to upload Bento "cancer_classifier:nfhcz6qtxkbedjcc"                                                                                                                                                   │
│ Failed pushing Bento "cancer_classifier:nfhcz6qtxkbedjcc": <html>                                                                                                                                             │
│ **<head><title>413 Request Entity Too Large</title></head>**                                                                                                                                                      │
│ <body>                                                                                                                                                                                                        │
│ **<center><h1>413 Request Entity Too Large</h1></center>**                                                                                                                                                        │
│ <hr><center>nginx</center>                                                                                                                                                                                    │
│ </body>                                                                                                                                                                                                       │
│ </html>                       

I had been trying to push an XGBOOST model also when i try to make deployment through yatai the deployment runs for ever
could you also please suggest a resolution for the above issue as well as that of pushing image into yatai
![yataid](https://user-images.githubusercontent.com/23618329/182877095-1642ddbe-e70b-4257-84ba-143cfbf450da.JPG)


Thanks,
Plaban Nayak

**Closed** 2022-11-21 16:40 UTC
